### PR TITLE
Add a gallery page (fixes #26)

### LINKED ISSUE #26: Showcase gallery of all styles
As discussed in [#19](https://github.com/rdnlsmith/vscode-linux-themes/issues/19#issuecomment-654117007):

> what do you think about a gallery page (i.e. another markdown file) with the names and screenshots of all themes?

> Yes, I think that is a good idea. In addition, I think it would be nice to also have a grid of smaller thumbnail images still in the README.
> I’d be interested to see if a version of [this site](https://vscodethemes.com/) could be run locally in order to generate thumbnails (the hosted version appears to be limited to a handful of themes per extension).

### PR DESCRIPTION
**Pull request by waldyrious**
Changes in this PR:
- Add a new gallery.md page
- Make the README screenshots smaller, and display them in a grid.
- Rename the screenshots to match the theme filenames
- Add a missing screenshot for the Elementary theme, based on the image from #19
- Trim the Adapta Nokto screenshot to remove the background

Preview links:
- [README](https://github.com/waldyrious/vscode-linux-themes/tree/gallery-page#linux-themes-for-visual-studio-code)
- [Gallery page](https://github.com/waldyrious/vscode-linux-themes/blob/gallery-page/gallery.md#gallery)

### CODE REVIEW

**Comment by rdnlsmith** [comment]
This looks great!

If I could make one suggestion&mdash;how about a link to the gallery above or below the grid? e.g. "See gallery.md for full-size screenshots."

Thanks for your help!

**Comment by waldyrious** [comment]
Of course! I should have thought of that. Will add a link right away.

**Comment by rdnlsmith** [comment]
Apologies for the close/reopen&mdash;first time trying to merge a PR from the mobile app. Thanks again!

**Comment by waldyrious** [comment]
No problem! I figured it was likely a mistake. By the way, out of curiosity — what's the deal with the discrepancy of the [`united-gnome.json`](https://github.com/rdnlsmith/vscode-linux-themes/blob/master/themes/dark/united-gnome.json) theme being named `United Ubuntu`? Shouldn't the names match?

**Comment by rdnlsmith** [comment]
That's a good question. That theme was made by the previous maintainer, and I haven't looked too closely at it. I believe you are right that it ought to be called United GNOME; I will fix it in time for the next release.

**Comment by rdnlsmith** [comment]
@waldyrious I will most likely be publishing a minor update in the next few days, so the new gallery grid will be appearing in the VS Code Marketplace. I typically tweet about new releases; would you like to be tagged in the tweet for attribution? And if so, what is your Twitter username?

**Comment by waldyrious** [comment]
I'd be honored to (even if for such a small contribution)! My Twitter username is the same as the github one :)

**Pull request merged**
